<?php

declare(strict_types=1);

use App\Core\FrontendAssets;
use App\Models\Setting;

test('public frontend delegates CSS and JS selection to the asset service', function (): void {
    $header = (string) file_get_contents(APP_ROOT . '/app/Views/site/_header.php');
    $footer = (string) file_get_contents(APP_ROOT . '/app/Views/site/_footer.php');

    assert_contains('FrontendAssets::styles()', $header);
    assert_contains('Asset::url($stylesheet)', $header);
    assert_contains('FrontendAssets::scripts()', $footer);
    assert_contains('Asset::url($script)', $footer);
});

test('asset service supports optimized mode and diagnostic source fallback', function (): void {
    Setting::set('perf_asset_bundle', '1');
    assert_same(['/assets/css/public.min.css'], FrontendAssets::styles());
    assert_same(['/assets/js/public.min.js'], FrontendAssets::scripts());

    Setting::set('perf_asset_bundle', '0');
    assert_same(6, count(FrontendAssets::styles()));
    assert_same(3, count(FrontendAssets::scripts()));
    assert_contains('/assets/css/frontend.css', implode(',', FrontendAssets::styles()));
    assert_contains('/assets/js/frontend.js', implode(',', FrontendAssets::scripts()));

    Setting::set('perf_asset_bundle', '1');
});

test('generated public bundles exist and stay within raw transfer guardrails', function (): void {
    $css = APP_ROOT . '/public/assets/css/public.min.css';
    $js = APP_ROOT . '/public/assets/js/public.min.js';

    assert_true(is_file($css), 'нет собранного public.min.css');
    assert_true(is_file($js), 'нет собранного public.min.js');
    $manifestPath = APP_ROOT . '/public/assets/asset-manifest.json';
    assert_true(is_file($manifestPath), 'нет manifest публичных ресурсов');
    $manifest = json_decode((string) file_get_contents($manifestPath), true);
    assert_true(is_array($manifest), 'manifest публичных ресурсов повреждён');

    // Обязательный порог — сжатый размер: именно его платит посетитель, и он же
    // проверяется в scripts/build-assets.mjs (cssBrotli/jsBrotli).
    assert_true(
        (int) ($manifest['css']['brotli'] ?? PHP_INT_MAX) <= 42 * 1024,
        'CSS bundle превысил 42 KiB brotli'
    );
    assert_true(
        (int) ($manifest['js']['brotli'] ?? PHP_INT_MAX) <= 18 * 1024,
        'JS bundle превысил 18 KiB brotli'
    );

    // Ограничение на несжатый размер — вспомогательное: оно ловит разрастание
    // темы (время разбора CSS браузером), но одной минификацией его уже не
    // удержать. Текущий потолок временный; цель — критический CSS и разделение
    // бандла по шаблонам, после которых порог нужно снизить.
    assert_true((int) filesize($css) <= 320 * 1024, 'CSS bundle превысил 320 KiB без сжатия');
    assert_true((int) filesize($js) <= 60 * 1024, 'JS bundle превысил 60 KiB без сжатия');
    assert_contains('Generated by npm run build:assets', (string) file_get_contents($css));
    assert_contains('Generated by npm run build:assets', (string) file_get_contents($js));
});

test('asset build is reproducible and checked by CI', function (): void {
    $package = json_decode((string) file_get_contents(APP_ROOT . '/package.json'), true);
    $workflow = (string) file_get_contents(APP_ROOT . '/.github/workflows/ci.yml');
    $script = (string) file_get_contents(APP_ROOT . '/scripts/build-assets.mjs');

    // Синхронизация вендорных ассетов выполняется перед бандлингом, поэтому в
    // скриптах есть префикс `npm run build:vendor`. Проверяем, что вызов
    // сборщика на месте, не привязываясь к точному составу цепочки команд.
    assert_contains('node scripts/build-assets.mjs', (string) ($package['scripts']['build:assets'] ?? ''));
    assert_contains('node scripts/build-assets.mjs --check', (string) ($package['scripts']['check:assets'] ?? ''));
    assert_contains('build:vendor', (string) ($package['scripts']['build:assets'] ?? ''));
    assert_contains('npm run check:assets', $workflow);
    assert_contains('asset-manifest.json', $script);
    assert_contains('cssBrotli:', $script);
    assert_contains('jsBrotli:', $script);
});

test('performance admin exposes bundle switch and compression status', function (): void {
    $controller = (string) file_get_contents(APP_ROOT . '/app/Controllers/Admin/PerformanceController.php');
    $view = (string) file_get_contents(APP_ROOT . '/app/Views/admin/performance/index.php');
    $status = FrontendAssets::status();

    assert_contains("Setting::set('perf_asset_bundle'", $controller);
    assert_contains('FrontendAssets::status()', $controller);
    assert_contains('name="perf_asset_bundle"', $view);
    assert_contains('Сжатие CSS и JavaScript', $view);
    assert_contains('Brotli', $view);
    assert_true(!empty($status['ready']), 'production-бандлы должны проходить быструю проверку');
    assert_true(!empty($status['current']), 'production-бандлы должны соответствовать исходникам');
});
