import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { brotliCompressSync, constants as zlibConstants, gzipSync } from 'node:zlib';
import process from 'node:process';
import CleanCSS from 'clean-css';
import { minify } from 'terser';

const cssSources = [
    'public/assets/css/fonts.css',
    'public/assets/css/gov-fonts.css',
    'public/assets/css/frontend.css',
    'public/assets/css/gov-theme.css',
    'public/assets/css/rich-content.css',
    'public/assets/css/a11y.css',
    'public/assets/css/public-layout-polish.css',
    'public/assets/css/public-editorial-pages.css',
];

const jsSources = [
    'public/assets/js/a11y.js',
    'public/assets/js/frontend.js',
    'public/assets/js/forms.js',
];

// Ассеты, подключаемые не на каждой странице (AssetCollector: JS_MAP, CSS_MAP,
// THEME_PART_MAP), в общий бандл не входят. Раньше они и не минифицировались —
// отдавались исходниками. Здесь они проходят ту же обработку, что и бандлы, и
// попадают в манифест отдельным разделом.
const blockSources = [
    'public/assets/css/blocks/news-detail.css',
    'public/assets/css/blocks/org-structure.css',
    'public/assets/js/blocks/slider.js',
    'public/assets/js/blocks/anchor_nav.js',
    'public/assets/js/news.js',
];

const minifiedName = (path) => path.replace(/\.(css|js)$/, '.min.$1');

const outputs = {
    css: 'public/assets/css/public.min.css',
    js: 'public/assets/js/public.min.js',
    manifest: 'public/assets/asset-manifest.json',
};

// Ориентиры сжатого размера. Это НЕ жёсткий порог: превышение печатается как
// предупреждение, сборка всё равно отдаёт бандлы. Раньше здесь бросалось
// исключение, и очередное дополнение темы просто ломало `npm run build:assets`.
// Цифры выбраны с запасом — они ловят аварию (например, случайно попавший в
// исходники несжатый вендорный файл), а не обычный рост стилей.
const budgets = {
    cssBrotli: 80 * 1024,
    jsBrotli: 40 * 1024,
};

const checkOnly = process.argv.includes('--check');

async function readSources(paths) {
    return Promise.all(paths.map(async (path) => ({
        path,
        // Keep fingerprints and generated artifacts identical on Windows and Linux.
        content: (await readFile(path, 'utf8')).replace(/\r\n?/g, '\n'),
    })));
}

function sizeReport(content) {
    const input = Buffer.from(content);
    return {
        raw: input.length,
        gzip: gzipSync(input, { level: 9 }).length,
        brotli: brotliCompressSync(input, {
            params: {
                [zlibConstants.BROTLI_PARAM_QUALITY]: 11,
            },
        }).length,
    };
}

function sha256(content) {
    return createHash('sha256').update(content).digest('hex');
}

function sourceFingerprint(sources) {
    const hash = createHash('sha256');
    for (const { path, content } of sources) {
        hash.update(path);
        hash.update('\0');
        hash.update(content);
        hash.update('\0');
    }
    return hash.digest('hex');
}

async function buildCss(sources) {
    const input = sources.map(({ path, content }) => `/* ${path} */\n${content}`).join('\n');
    const result = new CleanCSS({
        // Level 2 доводит оптимизацию до слияния и удаления дублирующихся
        // правил (около 8 KiB на текущем наборе). Реструктуризацию отключаем
        // осознанно: она переупорядочивает правила и при равной специфичности
        // способна изменить победителя каскада — для темы с большим числом
        // переопределений это неприемлемый риск ради нескольких байт.
        level: {
            1: {},
            2: { restructureRules: false, mergeSemantically: false },
        },
        rebase: false,
        returnPromise: false,
    }).minify(input);

    if (result.errors.length > 0) {
        throw new Error(`CSS build failed:\n${result.errors.join('\n')}`);
    }

    return `/*! Generated by npm run build:assets. Do not edit directly. */\n${result.styles}\n`;
}

async function buildJs(sources) {
    const input = Object.fromEntries(sources.map(({ path, content }) => [path, content]));
    const result = await minify(input, {
        compress: {
            passes: 2,
        },
        mangle: true,
        format: {
            comments: false,
        },
    });

    if (!result.code) {
        throw new Error('JavaScript build produced an empty file.');
    }

    return `/*! Generated by npm run build:assets. Do not edit directly. */\n${result.code}\n`;
}

async function verifyOrWrite(path, content) {
    if (!checkOnly) {
        await writeFile(path, content, 'utf8');
        return;
    }

    let current = '';
    try {
        current = (await readFile(path, 'utf8')).replace(/\r\n?/g, '\n');
    } catch {
        throw new Error(`${path} is missing. Run npm run build:assets.`);
    }
    if (current !== content) {
        throw new Error(`${path} is stale. Run npm run build:assets.`);
    }
}

/**
 * Минифицирует один файл блока. CSS проходит тот же CleanCSS, что и бандл;
 * JS — тот же terser. Возвращает запись для манифеста.
 */
async function buildBlockAsset(path) {
    const [{ content }] = await readSources([path]);
    const isCss = path.endsWith('.css');
    const output = minifiedName(path);
    const built = isCss
        ? await buildCss([{ path, content }])
        : await buildJs([{ path, content }]);

    await verifyOrWrite(output, built);

    return [`/${path.replace(/^public\//, '')}`, {
        path: `/${output.replace(/^public\//, '')}`,
        sourceSha256: sha256(content),
        sha256: sha256(built),
        ...sizeReport(built),
    }];
}

const [cssInput, jsInput] = await Promise.all([readSources(cssSources), readSources(jsSources)]);
const [css, js] = await Promise.all([buildCss(cssInput), buildJs(jsInput)]);
const blocks = Object.fromEntries(await Promise.all(blockSources.map(buildBlockAsset)));
const cssSize = sizeReport(css);
const jsSize = sizeReport(js);
const manifest = `${JSON.stringify({
    version: 1,
    generatedBy: 'npm run build:assets',
    css: {
        path: '/assets/css/public.min.css',
        sources: cssSources.map((path) => `/${path.replace(/^public\//, '')}`),
        sourceSha256: sourceFingerprint(cssInput),
        sha256: sha256(css),
        ...cssSize,
    },
    js: {
        path: '/assets/js/public.min.js',
        sources: jsSources.map((path) => `/${path.replace(/^public\//, '')}`),
        sourceSha256: sourceFingerprint(jsInput),
        sha256: sha256(js),
        ...jsSize,
    },
    // Ключ — исходный путь (как он записан в AssetCollector), значение —
    // минифицированный файл. FrontendAssets::blockAsset() подставляет его,
    // когда включена сборка бандлов.
    blocks,
}, null, 2)}\n`;
await Promise.all([
    verifyOrWrite(outputs.css, css),
    verifyOrWrite(outputs.js, js),
    verifyOrWrite(outputs.manifest, manifest),
]);

const mode = checkOnly ? 'verified' : 'built';
console.log(`Public assets ${mode}:`);
console.log(`  CSS ${cssSize.raw} raw / ${cssSize.gzip} gzip / ${cssSize.brotli} brotli`);
console.log(`  JS  ${jsSize.raw} raw / ${jsSize.gzip} gzip / ${jsSize.brotli} brotli`);
for (const [source, entry] of Object.entries(blocks)) {
    console.log(`  блок ${source} -> ${entry.raw} raw / ${entry.gzip} gzip / ${entry.brotli} brotli`);
}

// Превышение ориентира — только предупреждение: бандлы уже записаны и сайт
// продолжает собираться. Размер остаётся видимым в выводе и в manifest, так что
// рост заметен, но не блокирует работу над темой.
if (cssSize.brotli > budgets.cssBrotli) {
    console.warn(`  ВНИМАНИЕ: CSS ${cssSize.brotli} Б brotli — выше ориентира ${budgets.cssBrotli} Б.`);
}
if (jsSize.brotli > budgets.jsBrotli) {
    console.warn(`  ВНИМАНИЕ: JS ${jsSize.brotli} Б brotli — выше ориентира ${budgets.jsBrotli} Б.`);
}
